
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tippy)
```

## How Samuel bin Adiya, the Jewish hero, kept his word

::: {dir=rtl}


`r tippy("أَدْفَعُهَا", tooltip = "ـهَا<br>PRON<br>Gen=Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("أَمَانَتِي", tooltip = "ـِي<br>PRON<br>Gen=Masc|Number=Sing|Person=1|PronType=PersSuff")`
`r tippy("أَوْدَعَهَا", tooltip = "ـهَا<br>PRON<br>Gen=Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("أَيَّهُمَا", tooltip = "هُمَا<br>PRON<br>Gen=Masc|Number=Sing|Person=2|PronType=PersInd")`
`r tippy("إلَيْكَ", tooltip = "ـكَ<br>PRON<br>Gen=Masc|Number=Sing|Person=2|PronType=PersSuff")`
`r tippy("إِلَيْهِ", tooltip = "ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff<br>ـهُ<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("إِلَيْهِمُ", tooltip = "ـهُمْ<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("إِيَّاهُ", tooltip = "ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("بِإِنِّي", tooltip = "إِنَّ<br>PART<br><br>ـِي<br>PRON<br>Gen=Masc|Number=Sing|Person=1|PronType=PersSuff")`
`r tippy("بِالْوَفَآءِ", tooltip = "وَفَاءٌ<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("بِذِمَّتِي", tooltip = "ذِمَّةٌ (ذِمَمٌ ذِمَامٌ)<br>NOUN<br>Case=Gen|Definite=Cons|Gender=Fem|Number=Sing<br>ـِي<br>PRON<br>Gen=Masc|Number=Sing|Person=1|PronType=PersSuff")`
`r tippy("بِعَسْكَرِهِ", tooltip = "عَسْكَرٌ (عَسَاكِرُ)<br>NOUN<br>Case=ِGen|Definite=Cons|Gender=Masc|Number=Sing<br>ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("بِهِ", tooltip = "ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff<br>ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff<br>ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("حِصْنِهِ", tooltip = "ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("ذَبَحْتُهُ", tooltip = "ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("عَلَيَّ", tooltip = "ـِي<br>PRON<br>Gen=Masc|Number=Sing|Person=1|PronType=PersSuff")`
`r tippy("عِنْدَهُ", tooltip = "ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("غَيْرِهِ", tooltip = "ـهُ<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("فلَمّا", tooltip = "لَمَّا<br>CCONJ<br>")`
`r tippy("فَأَبَى", tooltip = "أَبَى يَأْبِي (إِبَاءَةٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فَإِنِّي", tooltip = "إِنَّ<br>PART<br><br>ـِي<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=1|PronType=PersSuff")`
`r tippy("فَاخْتَرْ", tooltip = "اخْتَارَ<br>VERB<br>Stem=VIII|ModAsp=Imp|Gender=Masc|Number=Sing|Person=2|Voice=Act")`
`r tippy("فَانْظُرْ", tooltip = "نَظَرَ يَنْظُرُ (نَظَرٌ)<br>VERB<br>Stem=I|ModAsp=Imp|Gender=Masc|Number=Sing|Person=2|Voice=Act")`
`r tippy("فَحَاصَرَهُ", tooltip = "حَاصَرَ<br>VERB<br>Stem=III|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act<br>ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("فَدَخَلَ", tooltip = "دَخَلَ يَدْخُلُ (دُخُولٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فَذَبَحَ", tooltip = "ذَبَحَ يَذْبَحُ (ذَبْحٌ)<br>VERB<br>Stem=I|ModAsp=Impf|Gender=Masc&Fem|Number=Sing|Person=1|Voice=Act<br>ـهُ<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("فَصَارَ", tooltip = "صَارَ يَصَارُ (مَصِيرٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فَظَفِرَ", tooltip = "ظَفِرَ يَظْفَرُ (ظَفَرٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فَعَاوَدَهُ", tooltip = "عَاوَدَ<br>VERB<br>Stem=III|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act<br>ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("فَقَالَ", tooltip = "قَالَ يَقُولُ (قَوْلٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act<br>قَالَ يَقُولُ (قَوْلٌ)<br>VERB<br>Stem=I|ModAsp=Imp|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فَلَمَّا", tooltip = "لَمَّا<br>CCONJ<br>")`
`r tippy("فَلَمَّا", tooltip = "لَمَّا<br>CCONJ<br>")`
`r tippy("قَصَدَهُ", tooltip = "ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("لَهُ", tooltip = "ـهُ<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("لِإِرْضَاءِ", tooltip = "أَرْضَى<br>NOUN<br>Case=Gen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("لِلدُّرُوعِ", tooltip = "دِرْعٌ (دُرُوعٌ)<br>NOUN<br>Case=Gen|Definite=Def|Gender=Masc&Fem|Number=Plur")`
`r tippy("لِلّٰه", tooltip = "اللهُ<br>NOUN<br>Case=Gen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("لِمُسْتَحِقِّهَا", tooltip = "اسْتَحَقَّ<br>PTCP<br>Stem=X|Case=Gen|Definite=Cons|Gender=Masc|Number=Sing|Voice=Act<br>ـهَا<br>PRON<br>Gen=Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("لِيَقْتُلَهُ", tooltip = "قَتَلَ يَقْتُلُ (قَتْلٌ)<br>VERB<br>Stem=I|ModAsp=Subj|Gender=Masc|Number=Sing|Person=3|Voice=Act<br>ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("مَوْتِهِ", tooltip = "ــــهُ<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("مِنْهَا", tooltip = "ـهَا<br>PRON<br>Gen=Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("والسِّلَاحَ", tooltip = "سِلَاحٌ (أَسْلِحَةٌ)<br>NOUN<br>Case=ِAcc|Definite=Def|Gender=Masc&Fem|Number=Sing")`
`r tippy("والسِّلَاحِ", tooltip = "سِلاَحٌ (أَسْلِحَةٌ)<br>NOUN<br>Case=Gen|Definite=Def|Gender=Masc&Fem|Number=Sing")`
`r tippy("وامْتَنَعَ", tooltip = "امْتَنَعَ<br>VERB<br>Stem=VIII|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("وَأَبَى", tooltip = "أَبَى يَأْبِي (إِبَاءَةٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("وَأَرَاهُ", tooltip = "أَرَى يَرَى (رَأْيٌ رُؤْيَةٌ)<br>VERB<br>Stem=IV|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act<br>ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَأَنْتَ", tooltip = "أَنْتَ<br>PRON<br>Gen=Masc|Number=Sing|Person=2|PronType=PersInd")`
`r tippy("وَإِلَّا", tooltip = "إِلَّا<br>PART<br>")`
`r tippy("وَإِنْ", tooltip = "إِنْ<br>CCONJ<br>")`
`r tippy("وَاسْتَأْسَرَهُ", tooltip = "اسْتَأَسَرَ<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act<br>ـهُ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَبَقَآئِهِ", tooltip = "بَقِيَ يَبْقَى (بَقَاءٌ)<br>NOUN<br>Case=ِGen|Definite=Cons|Gender=Masc|Number=Sing<br>ـهُ<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَحَضَرُوا", tooltip = "حَضَرَ يَحضُرُ (حُضُورٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("وَرَأى", tooltip = "رَأَى يَرَى (رَأْيٌ رُؤْيَةٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("وَرِعَايَةَ", tooltip = "رَعَى يَرْعَى (رَعْيٌ رِعَايَةٌ)<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Fem|Number=Sing")`
`r tippy("وَسِلَاحًا", tooltip = "سِلَاحٌ (أَسْلِحَةٌ)<br>NOUN<br>Case=Acc|Definite=Ind|Gender=Masc&Fem|Number=Sing")`
`r tippy("وَصَبَرَ", tooltip = "صَبَرَ يَصْبِرُ (صَبْرٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("وَعَهْدِي", tooltip = "عَهْدٌ (عُهُودٌ)<br>NOUN<br>Case=ِAcc|Definite=Cons|Gender=Masc|Number=Sing<br>ـِي<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=1|PronType=PersSuff")`
`r tippy("وَفَآئِي", tooltip = "ـِي<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=1|PronType=PersSuff")`
`r tippy("وَفَائِهِ", tooltip = "ـهُ<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَقَالَ", tooltip = "قَالَ يَقُولُ (قَوْلٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act<br>وَ<br>CCONJ<br>")`
`r tippy("وَكَانَ", tooltip = "كَانَ يَكُونُ (كَوْنٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("وَلَا", tooltip = "لَا<br>PART<br><br>لَا<br>PART<br>")`
`r tippy("وَلَدَكَ", tooltip = "ـكَ<br>PRON<br>Gen=Masc|Number=Sing|Person=2|PronType=PersSuff<br>ـكَ<br>PRON<br>Gen=Masc|Number=Sing|Person=2|PronType=PersSuff")`
`r tippy("وَلَدِهِ", tooltip = "ـهُ<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=3|PronType=PersSuff<br>ـهُ<br>PRON<br>Gen=Masc&Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَلَمْ", tooltip = "لَمْ<br>PART<br>")`
`r tippy("وَهُوَ", tooltip = "هُوَ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersInd")`
`r tippy("وَهْوَ", tooltip = "هُوَ<br>PRON<br>Gen=Masc|Number=Sing|Person=3|PronType=PersInd")`
`r tippy("قِيلَ", tooltip = "قَالَ يَقُولُ (قَوْلٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Pass")`
`r tippy("عِنْدَ", tooltip = "عِندَ<br>ADP<br>")`
`r tippy("طَافَ", tooltip = "طَافَ يَطُوفُ (طَوْفٌ طَوَافٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("بِهِ", tooltip = "بِـ<br>ADP<br>")`
`r tippy("حَوْلَ", tooltip = "حَوْلَ<br>ADP<br>")`
`r tippy("الْحِصْنِ", tooltip = "حِصْنٌ (حُصُونٌ)<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("وَهُوَ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("يُنَادِي", tooltip = "نَادَى<br>VERB<br>Stem=I|ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("السَّمَوْءَلَ", tooltip = "السَّمَوْءَلُ<br>NOUN<br>Case=ِAcc|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("بِإِنِّي", tooltip = "بِـ<br>ADP<br>")`
`r tippy("قَدْ", tooltip = "قَدْ<br>PART<br>")`
`r tippy("أَسَرْتُ", tooltip = "أَسَرَ يَأْسِرُ (أَسْرٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc&Fem|Number=Sing|Person=1|Voice=Act")`
`r tippy("السَّمَوْءَلِ", tooltip = "السَّمَوْءَلُ<br>NOUN<br>Case=Gen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("وَلَدَكَ", tooltip = "ولدٌ (أَوْلَادٌ)<br>NOUN<br>Case=ِAcc|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("وَإِنْ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("لَمْ", tooltip = "لَمْ<br>PART<br>")`
`r tippy("تُصَدِّقْ", tooltip = "صَدَّقَ<br>VERB<br>Stem=II|ModAsp=Juss|Gender=Masc|Number=Sing|Person=2|Voice=Act")`
`r tippy("فَانْظُرْ", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("إِلَيْهِ", tooltip = "إِلَى<br>ADP<br>")`
`r tippy("وَأَرَاهُ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("إِيَّاهُ", tooltip = "إِيَّا<br>PART<br>")`
`r tippy("وَقَالَ", tooltip = "قَالَ يَقُولُ (قَوْلٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("إِنْ", tooltip = "إِنْ<br>CCONJ<br>")`
`r tippy("بْنِ", tooltip = "ابْنٌ<br>NOUN<br>Case=Gen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("سَلَّمْتَ", tooltip = "سَلَّمَ<br>VERB<br>Stem=II|ModAsp=Perf|Gender=Masc|Number=Sing|Person=2|Voice=Act")`
`r tippy("إِلَيَّ", tooltip = "إِلَى<br>ADP<br>AdpType=Prep")`
`r tippy("الدُّرُوعَ", tooltip = "دِرْعٌ (دُرُوعٌ)<br>NOUN<br>Case=ِAcc|Definite=Def|Gender=Masc&Fem|Number=Sing")`
`r tippy("سَلَّمْتُ", tooltip = "سَلَّمَ<br>VERB<br>Stem=II|ModAsp=Perf|Gender=Masc|Number=Sing|Person=1|Voice=Act")`
`r tippy("إلَيْكَ", tooltip = "إِلَى<br>ADP<br>")`
`r tippy("وَلَدَكَ", tooltip = "ولدٌ (أَوْلَادٌ)<br>NOUN<br>Case=ِNom|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("وَإِلَّا", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("ذَبَحْتُهُ", tooltip = "ذَبَحَ يَذْبَحُ (ذَبْحٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc&Fem|Number=Sing|Person=1|Voice=Act")`
`r tippy("وَأَنْتَ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("تَنْظُرُ", tooltip = "نَظَرَ يَنْظُرُ (نَظَرٌ)<br>VERB<br>Stem=I|ModAsp=Impf|Gender=Masc|Number=Sing|Person=2|Voice=Act")`
`r tippy("عَادِيآءَ", tooltip = "عَادِيآءُ<br>NOUN<br>Case=Gen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("فَاخْتَرْ", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("أَيَّهُمَا", tooltip = "أَيٌّ<br>PART<br>")`
`r tippy("شِئْتَ", tooltip = "شَاءَ يَشَاءُ (مَشِيئَةٌ)<br>VERB<br>Aspect=Perf|Gender=Fem|Number=Sing|Person=3|Voice=Pass")`
`r tippy("فَقَالَ", tooltip = "فَـ<br>ADP<br>AdpType=Prep")`
`r tippy("السَّمَوْءَلُ", tooltip = "السَّمَوْءَلُ<br>NOUN<br>Case=ِNom|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("افْعَلْ", tooltip = "فَعَلَ يَفْعَلُ (فَِعْلٌ)<br>VERB<br>Stem=I|ModAsp=Imp|Gender=Masc|Number=Sing|Person=2|Voice=Act")`
`r tippy("مَا", tooltip = "مَا<br>PART<br>")`
`r tippy("شِئْتَ", tooltip = "شَاءَ يَشَاءُ (مَشِيئَةٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=2|Voice=Act")`
`r tippy("فَإِنِّي", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("لَا", tooltip = "لَا<br>PART<br>")`
`r tippy("فلَمّا", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("أُبْطِلُ", tooltip = "أَبْطَلَ<br>VERB<br>Stem=I|ModAsp=Impf|Gender=Masc&Fem|Number=Sing|Person=1|Voice=Act")`
`r tippy("وَفَآئِي", tooltip = "وَفَاءٌ<br>NOUN<br>Case=ِAcc|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("وَعَهْدِي", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("فَذَبَحَ", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("وَلَدَهُ", tooltip = "وَلَدَ (أَوْلَادٌ)<br>NOUN<br>Case=ِAcc|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("وَهْوَ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("يَنْظُرُ", tooltip = "نَظَرَ يَنْظُرُ (نَظَرٌ)<br>VERB<br>Stem=I|ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("ثُمَّ", tooltip = "ثُمَّ<br>PART<br>")`
`r tippy("لَمَّا", tooltip = "لَمَّا<br>CCONJ<br>")`
`r tippy("عَجَزَ", tooltip = "عَجَزَ يَعْجِزُ (عَجْزٌ)<br>VERB<br>Stem=I|ModAsp=Impf|Gender=Masc&Fem|Number=Sing|Person=1|Voice=Act")`
`r tippy("مَاتَ", tooltip = "مَاتَ يَمُوتُ (مَوْتٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("عَنْ", tooltip = "عَنْ<br>ADP<br>")`
`r tippy("فَتْحِ", tooltip = "فَتْحٌ يَفْتَحُ (فَتْحٌ)<br>NOUN<br>Case=ِGen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("الْحِصْنِ", tooltip = "حِصْنٌ (حُصُونٌ)<br>NOUN<br>Case=ِAcc|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("رَجَعَ", tooltip = "رَجَعَ يَرجِعُ (رُجُوعٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("خَآئِبًا", tooltip = "خَابَ يَخِيبُ (خَيْبَةٌ)<br>PTCP<br>Stem=I|Case=Acc|Definite=Ind|Gender=Masc|Number=Sing|Voice=Act")`
`r tippy("وَصَبَرَ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("السَّمَوْءَلُ", tooltip = "السَّمَوْءَلُ<br>NOUN<br>Case=ِAcc|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("عَلَى", tooltip = "عَلَى<br>ADP<br>")`
`r tippy("ذَبْحِ", tooltip = "ذَبَحَ يَذْبَحُ (ذَبْحٌ)<br>NOUN<br>Case=ِGen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("وَلَدِهِ", tooltip = "وَلَدٌ (أَوْلَادٌ)<br>NOUN<br>Case=ِGen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("أَرْسَلَ", tooltip = "أَرْسَلَ<br>VERB<br>Stem=IV|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("مُحَافَظَةً", tooltip = "حَافَظَ<br>NOUN<br>Case=ِAcc|Definite=Ind|Gender=Masc|Number=Sing")`
`r tippy("عَلَى", tooltip = "عَلَى<br>ADP<br>")`
`r tippy("وَفَائِهِ", tooltip = "وَفَاءٌ<br>NOUN<br>Case=ِGen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("فَلَمَّا", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("جَآء", tooltip = "جَاءَ يَجِيءُ (مَجِيءٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("وَرَثَةُ", tooltip = "وَرِثَ يَرِثُ (إِرْثٌ تُرَاثٌ)<br>PTCP<br>Stem=I|Case=Acc|Definite=Cons|Gender=Masc|Number=Sing|Voice=Act")`
`r tippy("امْرِءِ", tooltip = "امْرُءٌ<br>NOUN<br>Case=ِGen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("الْقَيْسِ", tooltip = "الْقَيْسُ<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("وَحَضَرُوا", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("عِنْدَ", tooltip = "عِنْدَ<br>ADP<br>")`
`r tippy("مَلِكُ", tooltip = "مَلِكٌ (مُلُوكٌ)<br>NOUN<br>Case=Nom|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("السَّمَوْءَلِ", tooltip = "السَّمَوْءَلُ<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("سَلَّمَ", tooltip = "سَلَّمَ<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("إِلَيْهِمُ", tooltip = "إِلَى<br>ADP<br>AdpType=Prep")`
`r tippy("الدُّرُوعَ", tooltip = "دِرْعٌ (دُرُوعٌ)<br>NOUN<br>Case=ِAcc|Definite=Def|Gender=Masc&Fem|Number=Plur")`
`r tippy("والسِّلَاحَ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("وَرَأى", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("حِفْظَ", tooltip = "حَفِظَ يَحْفَظُ (حِفْظٌ)<br>NOUN<br>Case=ِAcc|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("الذِّمَامِ", tooltip = "ذِمَّةٌ (ذِمَمٌ ذِمَامٌ)<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("وَرِعَايَةَ", tooltip = "وَ<br>CCONJ<br>Case=Acc|Definite=Cons|Number=Sing")`
`r tippy("الْوَفَآءِ", tooltip = "وَفَاءٌ<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("كِنْدَةَ", tooltip = "كِنْدَةُ<br>PROPN<br>Case=Gen|Definite=Ind|Gender=Fem|Number=Sing")`
`r tippy("أَحَبَّ", tooltip = "أَحَبَّ<br>ADJ<br>Case=Acc|Definite=Ind|Gender=Masc|Number=Sing")`
`r tippy("إِلَيْهِ", tooltip = "إِلَى<br>ADP<br>")`
`r tippy("مِنْ", tooltip = "مِنْ<br>ADP<br>")`
`r tippy("حَيٰوةِ", tooltip = "حَيٰوةٌ<br>NOUN<br>Case=ِGen|Definite=Cons|Gender=Fem|Number=Sing")`
`r tippy("وَلَدِهِ", tooltip = "وَلَدٌ (أَوْلَادٌ)<br>PRON<br>Case=ِGen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("وَبَقَآئِهِ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("فَصَارَ", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("ضَرْبُ", tooltip = "ضَرَبَ يَضْرِبُ (ضَرْبٌ)<br>NOUN<br>Case=ِNom|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("الْمَثَلِ", tooltip = "مَثَلٌ<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("بِالْوَفَآءِ", tooltip = "بِـ<br>ADP<br>")`
`r tippy("إِلَى", tooltip = "إِلَى<br>ADP<br>AdpType=Prep")`
`r tippy("لَهُ", tooltip = "لِـ<br>ADP<br>")`
`r tippy("دُونَ", tooltip = "دُونَ<br>ADP<br>")`
`r tippy("غَيْرِهِ", tooltip = "غَيْرٌ<br>PART<br>")`
`r tippy("أَنَّ", tooltip = "أَنَّ<br>CCONJ<br>")`
`r tippy("السَّمَوْءَلِ", tooltip = "السَّمَوْءَلُ<br>NOUN<br>Case=Gen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("رَسُولًا", tooltip = "رَسُولٌ (رُسُلٌ)<br>NOUN<br>Case=Acc|Definite=Ind|Gender=Masc|Number=Sing")`
`r tippy("طَالِبًا", tooltip = "طَلَبَ يَطْلُبُ (طَلَبٌ)<br>PTCP<br>Stem=I|Case=Acc|Definite=Ind|Gender=Masc|Number=Sing|Voice=Act")`
`r tippy("لِلدُّرُوعِ", tooltip = "لِ<br>ADP<br>AdpType=Prep")`
`r tippy("والسِّلَاحِ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("الَّتِي", tooltip = "الَّذِي<br>PRON<br>Gender=Fem|Number=Sing|PronType=Rel")`
`r tippy("أَوْدَعَهَا", tooltip = "أَوَدَعَ<br>VERB<br>Stem=IV|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("عِنْدَهُ", tooltip = "عِنْدَ<br>ADP<br>Case=Acc|Definite=Cons|Number=Sing")`
`r tippy("امْرُءُ", tooltip = "امْرُءٌ<br>NOUN<br>Case=Gen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("الْقَيْسِ", tooltip = "الْقُيْسُ<br>NOUN<br>Case=Gen|Definite=Def|Number=Plur")`
`r tippy("امْرَءَ", tooltip = "إِمْرُءٌ<br>PROPN<br>Case=Acc|Definite=Cons|Number=Sing")`
`r tippy("فَقَالَ", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("السَّمَوْءَلُ", tooltip = "السَّمَوْءَلُ<br>NOUN<br>Case=Nom|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("لا", tooltip = "لَا<br>PART<br>")`
`r tippy("أَدْفَعُهَا", tooltip = "دَفَعَ يَدْفَعُ (دَفْعٌ)<br>VERB<br>Stem=I|ModAsp=Impf|Gender=Masc|Number=Sing|Person=1|Voice=Act")`
`r tippy("إِلَّا", tooltip = "إِلَّا<br>PART<br>")`
`r tippy("لِمُسْتَحِقِّهَا", tooltip = "لِـ<br>ADP<br>")`
`r tippy("وَأَبَى", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("أَنْ", tooltip = "أَنْ<br>CCONJ<br>")`
`r tippy("يَدْفَعَ", tooltip = "دَفَعَ يَدْفَعُ (دَفْعٌ)<br>VERB<br>Stem=I|ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("شَيْــًٔا", tooltip = "شَيْءٌ (أَشْيَاءُ)<br>NOUN<br>Case=Acc|Definite=Ind|Gender=Masc|Number=Sing")`
`r tippy("الْقَيْسِ", tooltip = "الْقَيْسُ<br>PROPN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("مِنْهَا", tooltip = "مِنْ<br>ADP<br>")`
`r tippy("إِلَى", tooltip = "إِلَى<br>ADP<br>")`
`r tippy("رَسُولِ", tooltip = "رَسُولٌ (رُسُلٌ)<br>NOUN<br>Case=Gen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("الْمَلِكِ", tooltip = "مَلِكٌ (مُلُوكٌ)<br>NOUN<br>Case=Gen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("فَعَاوَدَهُ", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("فَأَبَى", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("أَيْضًا", tooltip = "أَيضًا<br>ADV<br>")`
`r tippy("وَقَالَ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("لِلّٰه", tooltip = "لِـ<br>ADP<br>")`
`r tippy("الْعَظِيمِ", tooltip = "عَظِيمٌ (عِظَامٌ عُظَمَاءُ)<br>ADJ<br>Case=Gen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("قَبْلَ", tooltip = "قَبلَ<br>ADP<br>")`
`r tippy("لَا", tooltip = "لَا<br>PART<br>")`
`r tippy("أَغْدُرُ", tooltip = "غَدَرَ يَغْدُِرُ (غَدْرٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc&Fem|Number=Sing|Person=1|Voice=Act")`
`r tippy("بِذِمَّتِي", tooltip = "بِـ<br>ADP<br>")`
`r tippy("وَلَا", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("أَخُونُ", tooltip = "خَانَ يَخُونُ (خَوْنٌ خِيَانَةٌ)<br>VERB<br>Stem=I|ModAsp=Impf|Gender=Masc&Fem|Number=Sing|Person=1|Voice=Act")`
`r tippy("أَمَانَتِي", tooltip = "أَمَانَةٌ<br>NOUN<br>Case=Acc|Definite=Cons|Gender=Fem|Number=Sing")`
`r tippy("وَلَا", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("أَتْرُكُ", tooltip = "تَرَكَ يَتْرُكُ (تَرْكٌ)<br>VERB<br>Stem=I|ModAsp=Impf|Gender=Masc&Fem|Number=Sing|Person=1|Voice=Act")`
`r tippy("الْوَفَآءَ", tooltip = "وَفَاءٌ<br>NOUN<br>Case=Acc|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("الْوَاجِبَ", tooltip = "وَجَبَ يَجِبُ (وُجُوبٌ)<br>PTCP<br>Stem=I|Case=Acc|Definite=Def|Gender=Masc|Number=Sing|Voice=Act")`
`r tippy("مَوْتِهِ", tooltip = "مَوْتٌ<br>NOUN<br>Case=Gen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("عَلَيَّ", tooltip = "عَلَى<br>ADP<br>")`
`r tippy("لِإِرْضَاءِ", tooltip = "لِـ<br>ADP<br>")`
`r tippy("الْمَلِكِ", tooltip = "مَلِكٌ (مُلُوكٌ)<br>NOUN<br>Case=Gen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("فَلَمَّا", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("بَلَّغَ", tooltip = "بَلَّغَ<br>VERB<br>Stem=II|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("الرَّسُولُ", tooltip = "رَسُولٌ (رُسُلٌ)<br>NOUN<br>Case=Nom|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("الْمَلِكَ", tooltip = "مَلِكٌ (مُلُوكٌ)<br>NOUN<br>Case=ِAcc|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("مَا", tooltip = "مَا<br>CCONJ<br>")`
`r tippy("قَالَ", tooltip = "قَالَ يَقُولُ (قَوْلٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("السَّمَوْءَلُ", tooltip = "السَّمَوْءَلُ<br>NOUN<br>Case=Nom|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("أَوْدَعَ", tooltip = "أَوْدَعَ<br>VERB<br>Stem=IV|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("قَصَدَهُ", tooltip = "قَصَدَ يَقْصُدُ (قَصْدٌ)<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("الْمَلِكُ", tooltip = "مَلِكٌ (مُلُوكٌ)<br>NOUN<br>Case=ِNom|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("بِعَسْكَرِهِ", tooltip = "بِـ<br>ADP<br>")`
`r tippy("فَدَخَلَ", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("السَّمَوْءَلُ", tooltip = "السَّمَوْءَلُ<br>NOUN<br>Case=Nom|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("فِي", tooltip = "فِي<br>ADP<br>")`
`r tippy("حِصْنِهِ", tooltip = "حِصْنٌ (حُصُونٌ)<br>NOUN<br>Case=ِGen|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("وامْتَنَعَ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("بِهِ", tooltip = "بِـ<br>ADP<br>")`
`r tippy("فَحَاصَرَهُ", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("دُرُوعًا", tooltip = "دِرْعٌ (دُرُوعٌ)<br>NOUN<br>Case=Acc|Definite=Ind|Gender=Com|Number=Plur")`
`r tippy("الْمَلِكُ", tooltip = "مَلِكٌ (مُلُوكٌ)<br>NOUN<br>Case=ِNom|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("وَكَانَ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("وَلَدُ", tooltip = "وَلَدٌ<br>NOUN<br>Case=ِNom|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("السَّمَوْءَلِ", tooltip = "السَّمَوْءَلُ<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("قَبْلَ", tooltip = "قَبلَ<br>ADP<br>")`
`r tippy("الْمُحَاصَرَةِ", tooltip = "حَاصَرَ<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Fem|Number=Sing")`
`r tippy("خَارِجَ", tooltip = "خَارِجَ<br>ADP<br>")`
`r tippy("الْحِصْنِ", tooltip = "حِصْنٌ (حُصُونٌ)<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Gen|Number=Sing")`
`r tippy("وَلَمْ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("يَحْضُرْ", tooltip = "حَضَرَ يَحضُرُ (حُضُورٌ)<br>VERB<br>Stem=I|ModAsp=Juss|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("وَسِلَاحًا", tooltip = "و<br>CCONJ<br>")`
`r tippy("حِينَ", tooltip = "حِينَ<br>ADP<br>")`
`r tippy("الْمُحَاصَرَةِ", tooltip = "حَاصَرَ<br>NOUN<br>Case=ِGen|Definite=Def|Gender=Fem|Number=Sing")`
`r tippy("لِيَقْتُلَهُ", tooltip = "لِـ<br>ADP<br>")`
`r tippy("الْمَلِكُ", tooltip = "مَلِكٌ (مُلُوكٌ)<br>NOUN<br>Case=ِNom|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("الْغَدَّارُ", tooltip = "غَدَّارٌ<br>NOUN<br>Case=ِNom|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("فَظَفِرَ", tooltip = "فَـ<br>CCONJ<br>")`
`r tippy("بِهِ", tooltip = "بِـ<br>ADP<br>")`
`r tippy("الْمَلِكُ", tooltip = "مَلِكٌ (مُلُوكٌ)<br>NOUN<br>Case=ِNom|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("وَاسْتَأْسَرَهُ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("ثُمَّ", tooltip = "ثُمَّ<br>CCONJ<br>")`
:::


## Словарь

::: {dir=rtl}


أَبْطَلَотменить, аннулировать; أَبَى يَأْبِي (إِبَاءَةٌ)отвергать, отказываться; أَحَبَّболее любимый; أَرْسَلَотправлять, посылать; أَرْضَىудовлетворять, угождать; أَرَى يَرَى (رَأْيٌ رُؤْيَةٌ)видеть; أَسَرَ يَأْسِرُ (أَسْرٌ)пленить, взять в плен; أَمَانَةٌвещь, отданная на хранение; أَنَّчто; أَنْчтобы; أَنْتَты (м.р.); أَوْدَعَдавать на сохранение; أَوَدَعَдавать на хранение; أَيٌّкакой; أَيضًاтакже, тоже; إِلَّاкроме, исключая; إِلَّاчаст. исключения; إِلَى; إِلَىна; إِلَىпо направлению к; إِلَىпред. выражающий дат.; إِمْرُءٌ(им.с.) Имру-ль-Кайс; إِنْесли; إِنَّчаст. усиления; إِيَّاчаст. прям. доп. для мест. суфф.; ابْنٌ(им.с.) ас-Самаваль ибн Адия; اخْتَارَвыбирать; اسْتَأَسَرَпленить, взять в плен; اسْتَحَقَّиметь право; الَّذِيкоторый; السَّمَوْءَلُ(им.с.) ас-Самаваль; السَّمَوْءَلُ(им.с.) ас-Самаваль ибн Адия; السَّمَوْءَلُас-Самаваль; السَّمَوْءَلُас-Самваль; الْقَيْسُ(им.с.) Имру-ль-Кайс; الْقُيْسُ(им.с.) Имру-ль-Кайс; اللهُБог; امْتَنَعَукрепиться; امْرُءٌ(им.с.) Имру-ль-Кайс; بِـ; بِـв; بِـвместе с; بِـс; بِـчего; بَقِيَ يَبْقَى (بَقَاءٌ)оставаться, сохраниться; بَلَّغَсообщать; تَرَكَ يَتْرُكُ (تَرْكٌ)отказываться; ثُمَّзатем; جَاءَ يَجِيءُ (مَجِيءٌ)приходить; حَاصَرَокружение; حَاصَرَокружить; حَافَظَзащищать (что عَلَى); حِصْنٌ (حُصُونٌ)крепость; حَضَرَ يَحضُرُ (حُضُورٌ)предстать, явиться; حَضَرَ يَحضُرُ (حُضُورٌ)присутствовать; حَفِظَ يَحْفَظُ (حِفْظٌ)сохранять, беречь; حَوْلَвокруг; حِينَ(временной союз) когда; حَيٰوةٌжизнь; خَابَ يَخِيبُ (خَيْبَةٌ)терпеть неудачу; خَارِجَза пределами, вне; خَانَ يَخُونُ (خَوْنٌ خِيَانَةٌ)не исполнять, нарушать; دَخَلَ يَدْخُلُ (دُخُولٌ)входить; دِرْعٌ (دُرُوعٌ)кольчуга; دَفَعَ يَدْفَعُ (دَفْعٌ)давать, отдавать; دَفَعَ يَدْفَعُ (دَفْعٌ)отдать; دُونَа не, кроме; ذَبَحَ يَذْبَحُ (ذَبْحٌ)зарезать; ذِمَّةٌ (ذِمَمٌ ذِمَامٌ)договор; رَأَى يَرَى (رَأْيٌ رُؤْيَةٌ)думать, считать, полагать; رَجَعَ يَرجِعُ (رُجُوعٌ)вернуться, возвратиться; رَسُولٌ (رُسُلٌ)посланник; رَعَى يَرْعَى (رَعْيٌ رِعَايَةٌ)следить, соблюдать; سِلاَحٌ (أَسْلِحَةٌ)оружие; سِلَاحٌ (أَسْلِحَةٌ)оружие; سَلَّمَпередать; سَلَّمَпередать; سَلَّمَпередать (кому إِلَى); شَاءَ يَشَاءُ (مَشِيئَةٌ)желать, хотеть; شَيْءٌ (أَشْيَاءُ)вещь, предмет; صَارَ يَصَارُ (مَصِيرٌ)стать, сделаться; صَبَرَ يَصْبِرُ (صَبْرٌ)терпеть (что عَلَى); صَدَّقَверить; ضَرَبَ يَضْرِبُ (ضَرْبٌ)приводить пример; طَافَ يَطُوفُ (طَوْفٌ طَوَافٌ)обходить вокруг; طَلَبَ يَطْلُبُ (طَلَبٌ)требовать; ظَفِرَ يَظْفَرُ (ظَفَرٌ)одлеть, одержать верх (над кем بِـ); عَادِيآءُ(им.с.) ас-Самаваль ибн Адия; عَاوَدَвозвращаться, повторять; عَجَزَ يَعْجِزُ (عَجْزٌ)быть не в состоянии сделать (что عَنْ); عَسْكَرٌ (عَسَاكِرُ)войско; عَظِيمٌ (عِظَامٌ عُظَمَاءُ)великий; عَلَى; عَنْ; عِنْدَперед; عِندَу; عِنْدَу; عَهْدٌ (عُهُودٌ)обещание, обет; غَدَّارٌпредатель; غَدَرَ يَغْدُِرُ (غَدْرٌ)изменять (кому-чему بِـ); غَيْرٌдругой; فَـзатем, и; فَـто; فَتْحٌ يَفْتَحُ (فَتْحٌ)завоевать; فَعَلَ يَفْعَلُ (فَِعْلٌ)делать; فِيв; قَالَ يَقُولُ (قَوْلٌ)сказать, произнести; قَالَ يَقُولُ (قَوْلٌ)сказать, произнести; говорить; قَبلَ(временной пред.) перед; до; قَبلَдо, прежде; قَتَلَ يَقْتُلُ (قَتْلٌ)убивать; قَدْчаст., выр. завершённость действия перед фор. перфекта; قَصَدَ يَقْصُدُ (قَصْدٌ)направляться; ـكَты (м.р.); كَانَ يَكُونُ (كَوْنٌ)быть; كِنْدَةُ(им.с.) Кинда; لِـ(част. цели) чтобы; لِпред. вводит прямое дополнение при причастии; لِـпред., в сочетании с сущ. и мест. соотвествует дат.; لِـчаст. клятвы; لَاчаст. отрицания; لَمْчаст. отрицания; لَمَّاкогда; لَمَّاкогда; مَاто (что); مَاто, (что); مَاتَ يَمُوتُ (مَوْتٌ)умереть; مَثَلٌприводить пример; مَلِكٌ (مُلُوكٌ)царь; مِنْот, из; مِنْчем; مَوْتٌсмерть; نَادَىзвать (какими словами بِـ); نَظَرَ يَنْظُرُ (نَظَرٌ)смотреть; ـهُего; ــــهُон; ـهُон; ـهُон (м.р.); ـهَاона; ـهُمْони (м.р.); هُمَاоба; هُوَон; وَзатем, и; وи; وَи; وَجَبَ يَجِبُ (وُجُوبٌ)быть обязытельным (для кого عَلَى); وَرِثَ يَرِثُ (إِرْثٌ تُرَاثٌ)наследовать; وَفَاءٌисполнение (обещания); وَفَاءٌиспроленение (обещания); ولدٌ (أَوْلَادٌ)ребёнок, сын; وَلَدٌ (أَوْلَادٌ)ребёнок, сын; وَلَدَ (أَوْلَادٌ)ребёнок, сын; وَلَدٌсын; ـِيя
:::


