
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tippy)
```
  
## The last raid

::: {dir=rtl}


`r tippy("كَانَ", tooltip = "كَانَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("مِنْ", tooltip = "مِنْ<br>ADP<br>AdpType=Prep")`
`r tippy("شَأْنِ", tooltip = "شَأْنٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("وَاسْمُهُ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("وَاسْمُهُ", tooltip = "اِسمٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Sing")`
`r tippy("وَاسْمُهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3")`
`r tippy("ثابِتُ بْنُ جابِرِ بْنِ سُفْيانَ", tooltip = "ثابِتُ بْنُ جابِرِ بْنِ سُفْيانَ<br>PROPN<br>")`
`r tippy("وَكانَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَكانَ", tooltip = "كانَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("نَهْداً", tooltip = "نَهْدٌ<br>ADJ<br>Case=Acc|Definite=Ind|Number=Sing|Gender=Masc")`
`r tippy("جَريئاً", tooltip = "جَريئٌ<br>ADJ<br>Case=Acc|Definite=Ind|Gender=Masc|Number=Sing")`
`r tippy("شاعِراً", tooltip = "شاعِرٌ<br>NOUN<br>Case=Acc|Definite=Ind|Number=Sing")`
`r tippy("فاتِكاً", tooltip = "فاتِكٌ<br>ADJ<br>Case=Acc|Definite=Ind|Gender=Masc|Number=Sing")`
`r tippy("أَنَّهُ", tooltip = "أنَّ<br>CCONJ<br>")`
`r tippy("أَنَّهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("خَرَجَ", tooltip = "خَرَجَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("مِنْ", tooltip = "مِنْ<br>ADP<br>AdpType=Prep")`
`r tippy("أَهْلِهِ", tooltip = "أَهْلٌ<br>NOUN<br>Case=Gen|Number=Sing|Definite=Cons")`
`r tippy("أَهْلِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("بِغارَةٍ", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِغارَةٍ", tooltip = "غارةٌ<br>NOUN<br>Case=Nom|Definite=Ind|Number=Sing")`
`r tippy("مِنْ", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("قَوْمِهِ", tooltip = "قَوْمٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("قَوْمِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("يُريدونَ", tooltip = "أَرَادَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Plur|Person=3|Voice=Act|Stem=IV")`
`r tippy("بَنى", tooltip = "إبْنٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Sing")`
`r tippy("صاهلة بِن كاهل بِن الحرث ابن تميم بِن سعد بِن هذيل", tooltip = "صاهلة بِن كاهل بِن الحرث ابن تميم بِن سعد بِن هذيل<br>PROPN<br>")`
`r tippy("وَذٰلِكَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَذٰلِكَ", tooltip = "ذٰلِكَ<br>PRON<br>Gender=Masc|Number=Sing|PronType=Dem")`
`r tippy("فِي", tooltip = "فِي<br>ADP<br>AdpType=Prep")`
`r tippy("عُقْبِ", tooltip = "عُقْبٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("شَهْرٍ", tooltip = "شَهْرٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("حَرَامٍ", tooltip = "حَرَامٌ<br>ADJ<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("مِمَّا", tooltip = "مِنْ<br>ADP<br>AdpType=Prep")`
`r tippy("مِمَّا", tooltip = "مَا<br>CCONJ<br>")`
`r tippy("كَانَ", tooltip = "كَانَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("يُحَرِّمُ", tooltip = "حَرَّمَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=II")`
`r tippy("أَهْلُ", tooltip = "أَهْلٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Sing")`
`r tippy("الْجَاهِلِيَّةِ", tooltip = "الْجَاهِلِيَّة<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("حَتَّى", tooltip = "حَتَّى<br>CCONJ<br>AdpType=Prep")`
`r tippy("هَبَطَ", tooltip = "هَبَطَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("صَدْرَ", tooltip = "صَدْرٌ<br>NOUN<br>Case=Acc|Definite=Cons|Number=Sing")`
`r tippy("إِدَامٍ", tooltip = "إِدَامٌ<br>PROPN<br>")`
`r tippy("وَخَفَّضَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَخَفَّضَ", tooltip = "خَفَّضَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=II")`
`r tippy("عَنْ", tooltip = "عَنْ<br>ADP<br>AdpType=Prep")`
`r tippy("جَمَاعَةِ", tooltip = "جَمَاعَةٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("بَنَى", tooltip = "إبْنٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Sing")`
`r tippy("نُفَاثَةَ بْنِ عَدِيٍّ", tooltip = "نُفَاثَةَ بْنِ عَدِيٍّ<br>PROPN<br>Case=Acc|Definite=Cons|Number=Sing")`
`r tippy("لَيْسَ", tooltip = "لَيْسَ<br>PART<br>Gender=Masc|Number=Sing|Person=3")`
`r tippy("فِيهَا", tooltip = "في<br>ADP<br>AdpType=Prep")`
`r tippy("فِيهَا", tooltip = "ها<br>PRON<br>Gender=Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("إِلَّا", tooltip = "إِلَّا<br>CCONJ<br>")`
`r tippy("النِّسَآءُ", tooltip = "مَرْأَةٌ<br>NOUN<br>Case=Nom|Definite=Def|Number=Plur")`
`r tippy("غَيْرَ", tooltip = "غَيْرَ<br>ADP<br>AdpType=Prep")`
`r tippy("رَجُلٍ", tooltip = "رَجُلٌ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("وَاحِدٍ", tooltip = "وَاحِدٌ<br>NUM<br>Case=Gen|Definite=Ind|Gender=Masc|NumValue=1")`
`r tippy("فَبَصُرَ", tooltip = "فَ<br>CCONJ<br>")`
`r tippy("فَبَصُرَ", tooltip = "بَصُرَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("الرَّجُلُ", tooltip = "رَجُلٌ<br>NOUN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("بِتَأَبَّطَ شَرّاً", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِتَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("فَخَشِيَهُ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَخَشِيَهُ", tooltip = "خَشِيَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فَخَشِيَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَذٰالِكَ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("وَذٰالِكَ", tooltip = "ذلِكَ<br>PRON<br>Gender=Masc|Number=Sing|PronType=Dem")`
`r tippy("فِي", tooltip = "فِي<br>ADP<br>")`
`r tippy("الضَّحآءِ", tooltip = "ضَحآءُ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("فَقَامَ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَقَامَ", tooltip = "قامَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("الرَّجُلُ", tooltip = "رَجُلٌ<br>NOUN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("إِلَى", tooltip = "إِلَى<br>ADP<br>")`
`r tippy("النِّسَآءِ", tooltip = "مَرْأَةٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Plur")`
`r tippy("فَأَمَرَهُنَّ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَأَمَرَهُنَّ", tooltip = "أمَرَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فَأَمَرَهُنَّ", tooltip = "هُنَّ<br>PRON<br>Gender=Fem|Number=Plur|Person=3|PronType=PersSuff")`
`r tippy("فَجَعَلْنَ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَجَعَلْنَ", tooltip = "جَعَلَ<br>VERB<br>ModAsp=Perf|Gender=Fem|Number=Plur|Person=3|Voice=Act")`
`r tippy("رَؤُوسَهُنَّ", tooltip = "رَأسٌ<br>NOUN<br>Case=Acc|Definite=Cons|Number=Plur")`
`r tippy("رَؤُوسَهُنَّ", tooltip = "هُنَّ<br>PRON<br>Gender=Fem|Number=Plur|Person=3|PronType=PersSuff")`
`r tippy("جُمَماً", tooltip = "جُمّةٌ<br>NOUN<br>Case=Acc|Definite=Ind|Number=Plur")`
`r tippy("وَجَعَلْنَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَجَعَلْنَ", tooltip = "جَعَلَ<br>VERB<br>ModAsp=Perf|Gender=Fem|Number=Plur|Person=3|Voice=Act")`
`r tippy("دُرُوعَهُنَّ", tooltip = "دِرْعٌ<br>NOUN<br>Case=Acc|Gender=Fem|Number=Plur|Definite=Cons")`
`r tippy("دُرُوعَهُنَّ", tooltip = "هُنَّ<br>PRON<br>Gender=Fem|Number=Plur|Person=3|PronType=PersSuff")`
`r tippy("أَرْدِيَةً", tooltip = "رِدآءٌ<br>NOUN<br>Case=Acc|Definite=Indef|Number=Plur")`
`r tippy("وَاتَّخَذْنَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَاتَّخَذْنَ", tooltip = "اِتَّخَذَ<br>VERB<br>ModAsp=Perf|Gender=Fem|Number=Plur|Person=3|Voice=Act|Stem=VIII")`
`r tippy("مِنْ", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("بُيُوتِهِنَّ", tooltip = "بَيْتٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Plur")`
`r tippy("بُيُوتِهِنَّ", tooltip = "هُنَّ<br>PRON<br>Gender=Fem|Number=Plur|Person=3|PronType=PersSuff")`
`r tippy("عَمَداً", tooltip = "عُمُودٌ<br>NOUN<br>Case=Acc|Definite=Indef|Number=Plur")`
`r tippy("كَهَيْئَةِ", tooltip = "كَ<br>PART<br>")`
`r tippy("كَهَيْئَةِ", tooltip = "هَيْئَةٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("السُّيُوفِ", tooltip = "سَيْفٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Plur")`
`r tippy("فَجَعَلَ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَجَعَلَ", tooltip = "خَعَلَ<br>VERB<br>ModAsp=Perf|Gender=Fem|Number=Plur|Person=3|Voice=Act")`
`r tippy("لَهَا", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لَهَا", tooltip = "ها<br>PRON<br>Gender=Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("حَمَآئِلَ", tooltip = "حِمالَةٌ<br>NOUN<br>Case=Acc|Definite=Cons|Number=Plur")`
`r tippy("ثُمَّ", tooltip = "ثُمَّ<br>CCONJ<br>")`
`r tippy("تَأَبَّطْنَهَا", tooltip = "تَأَبَّطَ<br>VERB<br>ModAsp=Perf|Gender=Fem|Number=Plur|Person=3|Voice=Act|Stem=V")`
`r tippy("تَأَبَّطْنَهَا", tooltip = "ها<br>PRON<br>Gender=Fem|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("ثُمَّ", tooltip = "ثُمَّ<br>CCONJ<br>")`
`r tippy("نَهَضَ", tooltip = "نَهَضَ<br>VERB<br>ModAsp=Perf|Gender=Fem|Number=Plur|Person=3|Voice=Act")`
`r tippy("وَنَهْضَ", tooltip = "وَ<br>CCONJ<br>")`
`r tippy("وَنَهْضَ", tooltip = "نَهَضَ<br>VERB<br>ModAsp=Perf|Gender=Fem|Number=Plur|Person=3|Voice=Act")`
`r tippy("مَعَهُ", tooltip = "مع<br>ADP<br>AdpType=Prep")`
`r tippy("مَعَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("يُغْرِيهِنَّ", tooltip = "أَغرَى<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=IV")`
`r tippy("يُغْرِيهِنَّ", tooltip = "هن<br>PRON<br>Gender=Fem|Number=Plur|Person=3|PronType=PersSuff")`
`r tippy("كَمَا", tooltip = "كَمَا<br>CCONJ<br>")`
`r tippy("يُغْرِي", tooltip = "أَغرَى<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=IV")`
`r tippy("الْقَوْمَ", tooltip = "قَوْمٌ<br>NOUN<br>Case=Acc|Definite=Def|Number=Sing")`
`r tippy("وَيَصِيحُ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَيَصِيحُ", tooltip = "صاحَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("عَلَى", tooltip = "عَلَى<br>ADP<br>AdpType=Prep")`
`r tippy("الْقَوْمِ", tooltip = "قَوْمٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("حَتَّى", tooltip = "حَتَّى<br>ADP<br>AdpType=Prep")`
`r tippy("أَفْزَعَ", tooltip = "أَفزَع<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=IV")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("وَأَصْحَابَهُ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَأَصْحَابَهُ", tooltip = "صاحِبٌ<br>NOUN<br>Case=Acc|Definite=Cons|Number=Plur")`
`r tippy("وَأَصْحَابَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَهُوَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَهُوَ", tooltip = "هُوَ<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=Prs")`
`r tippy("عَلَى", tooltip = "عَلَى<br>ADP<br>AdpType=Prep")`
`r tippy("ذٰلِكَ", tooltip = "ذٰلِكَ<br>DET<br>Gender=Masc|Number=Sing")`
`r tippy("فِي", tooltip = "فِي<br>ADP<br>AdpType=Prep")`
`r tippy("بَقِيَّةِ", tooltip = "بَقِيَّةٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("لَيْلَةٍ", tooltip = "لَيلَةٌ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("أَوْ", tooltip = "أَو<br>CCONJ<br>")`
`r tippy("لَيْلَتَيْنِ", tooltip = "لَيْلةٌ<br>ADJ<br>Case=Gen|Definite=Ind|Number=Dual")`
`r tippy("مِنَ", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("الشَّهْرِ", tooltip = "شَهْرٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("الْحَرَامِ", tooltip = "حَرَامٌ<br>ADJ<br>Case=Gen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("فَنَهَضُوا", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَنَهَضُوا", tooltip = "نَهَضَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("فِي", tooltip = "فِي<br>ADP<br>AdpType=Prep")`
`r tippy("شِعْبٍ", tooltip = "شِعْبٌ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("يُقَالُ", tooltip = "قَال<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Pass")`
`r tippy("لَهُ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَشَلٌ", tooltip = "وَشَلٌ<br>PROPN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("وَجَعَلَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَجَعَلَ", tooltip = "جَعَلَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("يَنْهَضُ", tooltip = "نَهَضَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فِي", tooltip = "فِي<br>ADP<br>AdpType=Prep")`
`r tippy("الشِّعْبِ", tooltip = "شِعْبٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("مَعَ", tooltip = "مَعَ<br>ADP<br>AdpType=Prep")`
`r tippy("أَصْحَابِهِ", tooltip = "صاحِبٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Plur")`
`r tippy("أَصْحَابِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("ثُمَّ", tooltip = "ثُمَّ<br>CCONJ<br>")`
`r tippy("يَقِفُ", tooltip = "وَقَفَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فِي", tooltip = "فِي<br>ADP<br>AdpType=Prep")`
`r tippy("آخِرِهِمْ", tooltip = "آخِرٌ<br>ADJ<br>Case=Gen|Gender=Masc|Number=Plur")`
`r tippy("آخِرِهِمْ", tooltip = "هم<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("ثُمَّ", tooltip = "ثُمَّ<br>CCONJ<br>")`
`r tippy("يَقُولُ", tooltip = "قالَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("يَا", tooltip = "يَا<br>PART<br>")`
`r tippy("قَوْمِ", tooltip = "قَوْمٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("لَكَأَنَّمَا", tooltip = "ل<br>ADP<br>")`
`r tippy("لَكَأَنَّمَا", tooltip = "كَأَنَّمَا<br>CCONJ<br>")`
`r tippy("تَطْرُدُكُمُ", tooltip = "طَرَدَ<br>VERB<br>ModAsp=Impf|Gender=Fem|Number=Plur|Person=3|Voice=Act")`
`r tippy("تَطْرُدُكُمُ", tooltip = "كُمْ<br>PRON<br>Gender=Masc|Number=Plur|Person=2")`
`r tippy("النِّسَآءُ", tooltip = "مرأة<br>NOUN<br>Case=Nom|Definite=Def|Number=Plur")`
`r tippy("فَيَصِيحُ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَيَصِيحُ", tooltip = "صاحَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("عَلَيْهِ", tooltip = "عَلى<br>ADP<br>AdpType=Prep")`
`r tippy("عَلَيْهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("أَصْحَابُهُ", tooltip = "صاحِبٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Plur")`
`r tippy("أَصْحَابُهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَيَقُولُونَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَيَقُولُونَ", tooltip = "قالَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("انْجُ", tooltip = "نَجَا<br>VERB<br>Stem=I|ModAsp=Imp|Gender=Masc|Number=Sing|Person=2|Voice=Act")`
`r tippy("أَدْرَكَكَ", tooltip = "أَدْرَكَ<br>VERB<br>Stem=IV|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("أَدْرَكَكَ", tooltip = "ـكَ<br>PRON<br>Gender=Masc|Number=Sing|Person=2|PronType=PersSuff")`
`r tippy("الْقَوْمِ", tooltip = "قَوْمٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("وَتَأْبَى", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَتَأْبَى", tooltip = "أَبَى<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=2|Voice=Act")`
`r tippy("نَفْسُهُ", tooltip = "نَفْسٌ<br>PRON<br>Number=Sing")`
`r tippy("نَفْسُهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("فَلَمْ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَلَمْ", tooltip = "لَمْ<br>PART<br>")`
`r tippy("يَزَلْ", tooltip = "زَالَ<br>VERB<br>ModAsp=Juss|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("بِهِ", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("أَصْحَابُهُ", tooltip = "صاحِبٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Plur")`
`r tippy("أَصْحَابُهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("حَتَّى", tooltip = "حَتَّى<br>ADP<br>AdpType=Prep")`
`r tippy("مَضَى", tooltip = "مَضَى<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("مَعَهُمُ", tooltip = "مَعَ<br>ADP<br>AdpType=Prep")`
`r tippy("مَعَهُمُ", tooltip = "هُمْ<br>PRON<br>Gender=Masc|Number=Plur|Person=3|PronType=PersSuff")`
`r tippy("وَلَمَّا", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَلَمَّا", tooltip = "لَمَّا<br>CCONJ<br>")`
`r tippy("انْكَشَفَ", tooltip = "اِنكَشَفَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=VII")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("عَنْ", tooltip = "عَنْ<br>ADP<br>AdpType=Prep")`
`r tippy("بَنِي نُفَاثَةَ", tooltip = "بَنِي نُفَاثَةَ<br>PROPN<br>")`
`r tippy("طَلَعَ", tooltip = "طَلَعَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("مِنْ", tooltip = "مِنْ<br>ADP<br>AdpType=Prep")`
`r tippy("رَأَسِ", tooltip = "رَأسٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("إِحِلِيلٍ", tooltip = "إحْليلٌ<br>PROPN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("فَمَرَّ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَمَرَّ", tooltip = "مَرَّ<br>NOUN<br>Aspect=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("عَلَى", tooltip = "عَلَى<br>ADP<br>AdpType=Prep")`
`r tippy("رَجُلٍ", tooltip = "رَجُلٌ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("مِنْ", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("بَنِي قُرَيِمٍ", tooltip = "بَنِي قريم<br>PROPN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("مِنْ", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("بَيْنَ", tooltip = "بَينَ<br>ADP<br>AdpType=Prep")`
`r tippy("الْجَبَلَيْنِ", tooltip = "جَبَلٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Dual")`
`r tippy("يُقَالُ", tooltip = "قَالَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Pass")`
`r tippy("لَهُ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("جُنْدَبُ بْنُ الْحٰرِثِ", tooltip = "جُنْدَبُ بْنُ الْحٰرِثِ<br>PROPN<br>")`
`r tippy("وَمَعَهُ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَمَعَهُ", tooltip = "مع<br>ADP<br>AdpType=Prep")`
`r tippy("وَمَعَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("جَارٌ", tooltip = "جَارٌ<br>NOUN<br>Case=Nom|Definite=Ind|Number=Sing")`
`r tippy("لَهُ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("مِنْ", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("عَدْوَانَ", tooltip = "عَدْوَانُ<br>PROPN<br>")`
`r tippy("يُقَالُ", tooltip = "قَالَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Pass")`
`r tippy("لَهُ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("صُرَيْمٌ", tooltip = "صُرَيْمٌ<br>PROPN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("وَكَانَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَكَانَ", tooltip = "كانَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("القُرَمِيُّ", tooltip = "القُرَمِيُّ<br>PROPN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("رَجُلاً", tooltip = "رَجُلٌ<br>NOUN<br>Case=Acc|Definite=Ind|Number=Sing")`
`r tippy("كَثِيرَ", tooltip = "كَثِيرٌ<br>ADJ<br>Case=Acc|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("الْمَالِ", tooltip = "مَالٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("أَكْثَرَ", tooltip = "كَثِيرٌ<br>ADJ<br>Case=Acc|Definite=Cons|Gender=Masc|Number=Sing|Elat")`
`r tippy("أَهْلِ", tooltip = "أَهلٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("بِلَادِهِ", tooltip = "بَلَدٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Plur")`
`r tippy("بِلَادِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("مَالاً", tooltip = "مالٌ<br>NOUN<br>Case=Acc|Definite=Ind|Number=Sing")`
`r tippy("وَكَانَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَكَانَ", tooltip = "كانَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("رَجُلاً", tooltip = "رَجُلٌ<br>NOUN<br>Case=Acc|Definite=Ind|Number=Sing")`
`r tippy("سِلْماً", tooltip = "سِلْمٌ<br>NOUN<br>Case=Acc|Definite=Ind|Number=Sing")`
`r tippy("لِلنّاسِ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لِلنّاسِ", tooltip = "إنْسانٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Plur")`
`r tippy("كُلِّهِمْ", tooltip = "كل<br>PRON<br>")`
`r tippy("كُلِّهِمْ", tooltip = "هُمْ<br>PRON<br>Gender=Masc|Number=Plur|Person=3|PronType=PersSuff")`
`r tippy("يُدْعَى", tooltip = "دَعا<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Pass")`
`r tippy("لِذٰلِكَ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لِذٰلِكَ", tooltip = "ذلِكَ<br>PRON<br>Gender=Masc|Number=Sing|PronType=Dem")`
`r tippy("النُّوَيْعِمَ", tooltip = "النُوَيْعِمٌ<br>PROPN<br>")`
`r tippy("لِنِعْمَتِهِ", tooltip = "لِ<br>ADP<br>AdpType=Prep")`
`r tippy("لِنِعْمَتِهِ", tooltip = "نِعْمةٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("لِنِعْمَتِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَكَانَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَكَانَ", tooltip = "كانَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("صُرَيْمٌ", tooltip = "صُرَيْمٌ<br>PROPN<br>")`
`r tippy("حَلِيفاً", tooltip = "حَلِيفٌ<br>ADJ<br>Case=Acc|Definite=Ind|Gender=Masc|Number=Sing")`
`r tippy("لِجُنْدَبٍ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لِجُنْدَبٍ", tooltip = "جُنْدَبٌ<br>PROPN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("فَلَمَّا", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَلَمَّا", tooltip = "لَمَّا<br>CCONJ<br>")`
`r tippy("مَرَّ", tooltip = "مَرَّ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("بِهِمَا", tooltip = "بِ<br>ADP<br>AdpType=Prep")`
`r tippy("بِهِمَا", tooltip = "هُما<br>PRON<br>Gender=Masc|Number=Dual|Person=3|PronType=PersSuff")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("دَعَا", tooltip = "دَعَا<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("أَصْحَابَهُ", tooltip = "صاحِبٌ<br>NOUN<br>Case=Acc|Definite=Cons|Number=Plur")`
`r tippy("أَصْحَابَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("لِأَنْ", tooltip = "لِأَنْ<br>CCONJ<br>")`
`r tippy("يَغْدِرُوا", tooltip = "غَدَرَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("بِهِمَا", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِهِمَا", tooltip = "هُما<br>PRON<br>Gender=Masc|Number=Dual|Person=3|PronType=PersSuff")`
`r tippy("فَأَبَى", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَأَبَى", tooltip = "أَبَى<br>VERB<br>Stem=I|ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("عَلَيْهِ", tooltip = "على<br>ADP<br>AdpType=Prep")`
`r tippy("عَلَيْهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("أَصْحَابُهُ", tooltip = "صاحِبٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Plur")`
`r tippy("أَصْحَابُهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("فَرَزَّ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَرَزَّ", tooltip = "رَزَّ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("سَهْماً", tooltip = "سَهْمٌ<br>NOUN<br>Case=Acc|Definite=Ind|Number=Sing")`
`r tippy("بِسَاحَتِهِما", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِسَاحَتِهِما", tooltip = "ساحةٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("بِسَاحَتِهِما", tooltip = "هُما<br>PRON<br>Gender=Masc|Number=Dual|Person=3|PronType=PersSuff")`
`r tippy("وَكانَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَكانَ", tooltip = "كانَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("ذٰلِكَ", tooltip = "ذٰلِكَ<br>PRON<br>Gender=Masc|Number=Sing|PronType=Dem")`
`r tippy("مِنْ", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("فِعْلِ", tooltip = "فِعْلٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("أَهْلِ", tooltip = "أَهْلٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("الْجَاهِلِيَّةِ", tooltip = "الْجَاهِلِيَّةُ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("فَتَعَدَّوْا", tooltip = "فَ<br>CCONJ<br>")`
`r tippy("فَتَعَدَّوْا", tooltip = "تَعَدَّى<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Plur|Person=3|Voice=Act|Stem=V")`
`r tippy("عَنْهُمَا", tooltip = "عَنْ<br>ADP<br>AdpType=Prep")`
`r tippy("عَنْهُمَا", tooltip = "هُما<br>PRON<br>Gender=Masc|Number=Dual|Person=3|PronType=PersSuff")`
`r tippy("ثُمَّ", tooltip = "ثُمَّ<br>CCONJ<br>")`
`r tippy("طَلَعُوا", tooltip = "طَلَعَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("لِمَصْدَرِ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لِمَصْدَرِ", tooltip = "مَصْدَرٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("حُثُنٍ", tooltip = "حُثُنٍ<br>PROPN<br>")`
`r tippy("فَوَجَدُو", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَوَجَدُوا", tooltip = "وَجَدَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("أَهْلَ", tooltip = "أَهْلٌ<br>NOUN<br>Case=Acc|Definite=Cons|Number=Sing")`
`r tippy("بَيْتٍ", tooltip = "بَيْتٌ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("شَاذٍّ", tooltip = "شاذٌ<br>ADJ<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("مِنْ", tooltip = "مِنْ<br>ADP<br>AdpType=Prep")`
`r tippy("بَنِي قُرَيْمٍ", tooltip = "بَنِي قُرَيْمٍ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Plur")`
`r tippy("ذَنَبَ", tooltip = "ذَنَبٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("نُمارٍ", tooltip = "نمارٌ<br>PROPN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("فَظَلَّ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَظَلَّ", tooltip = "ظلّ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("يُرَاقِبُهُمْ", tooltip = "راقَبَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=III")`
`r tippy("يُرَاقِبُهُمْ", tooltip = "هُمْ<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("حَتَّى", tooltip = "حَتَّى<br>CCONJ<br>")`
`r tippy("أَمْسَوْا", tooltip = "أَمسى<br>VERB<br>Aspect=Perf|Gender=Masc|Number=Plur|Person=3|Voice=Act|Stem=IV")`
`r tippy("وذٰلِكَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وذٰلِكَ", tooltip = "ذلِكَ<br>PRON<br>Gender=Masc|Number=Sing|PronType=Dem")`
`r tippy("الْبَيْتُ", tooltip = "بَيْتٌ<br>NOUN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("لِسَاعِدةَ بْنِ سُفْيَانَ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لِسَاعِدةَ بْنِ سُفْيَانَ", tooltip = "سَاعِدةَ بْنِ سُفْيَانَ<br>PROPN<br>Gender=Masc")`
`r tippy("أَحَدِ", tooltip = "أَحَدٌ<br>NUM<br>Case=Gen|Definite=Cons|Gender=Masc|NumValue=1")`
`r tippy("بَنِي حَارِثَةَ بْنِ قُرَيْمٍ", tooltip = "بَنِي حَارِثَةَ بْنِ قُرَيْمٍ<br>PROPN<br>")`
`r tippy("فَحَصَرَهُمْ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَحَصَرَهُمْ", tooltip = "حَصَرَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فَحَصَرَهُمْ", tooltip = "هُمْ<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("وَأَصْحَابُهُ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَأَصْحَابُهُ", tooltip = "صاحِبٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Plur")`
`r tippy("وَأَصْحَابُهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("حَتَّى", tooltip = "حَتَّى<br>CCONJ<br>")`
`r tippy("أَمْسَوْا", tooltip = "أَمْسَى<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Plur|Person=3|Voice=Act|Stem=IV")`
`r tippy("وَقَدْ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَقَدْ", tooltip = "قَدْ<br>PART<br>")`
`r tippy("قَالَتْ", tooltip = "قَالَ<br>VERB<br>ModAsp=Perf|Gender=Fem|Number=Sing|Person=3|Voice=Act")`
`r tippy("وَلِيدَةٌ", tooltip = "وَلِيدَةٌ<br>NOUN<br>Case=Nom|Definite=Ind|Number=Sing")`
`r tippy("لِسَاعِدَةَ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لِسَاعِدَةَ", tooltip = "ساعِدَةٌ<br>PROPN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("لِسَيِّدِهَا", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لِسَيِّدِهَا", tooltip = "سَيِّدٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("لِسَيِّدِهَا", tooltip = "ها<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("يَا", tooltip = "يَا<br>PART<br>")`
`r tippy("سَيَّدِي", tooltip = "سَيِّدٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Sing")`
`r tippy("سَيَّدِي", tooltip = "ي<br>PRON<br>Number=Sing|Person=1|PronType=PersSuff")`
`r tippy("قَدْ", tooltip = "قَد<br>PART<br>")`
`r tippy("رَأَيْتُ", tooltip = "رأى<br>VERB<br>ModAsp=Perf|Number=Sing|Person=1|Voice=Act")`
`r tippy("الْيَوْمَ", tooltip = "الْيَوْمَ<br>ADV<br>")`
`r tippy("الْقَوْمَ", tooltip = "قَوْمٌ<br>NOUN<br>Case=Acc|Definite=Def|Number=Sing")`
`r tippy("أَوِ", tooltip = "أَوْ<br>CCONJ<br>")`
`r tippy("الْبَقَرَ", tooltip = "بَقَرٌ<br>NOUN<br>Case=Acc|Definite=Def|Number=Sing")`
`r tippy("بِهٰذَا", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِهٰذَا", tooltip = "هذا<br>PRON<br>Gender=Masc|Number=Sing|PronType=Dem")`
`r tippy("الْجَبَلِ", tooltip = "جَبَلٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("فَبَاتَ", tooltip = "فَ<br>CCONJ<br>")`
`r tippy("فَبَاتَ", tooltip = "بَاتَ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("الْشَّيْخُ", tooltip = "شَيْخٌ<br>NOUN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("حَاذِراً", tooltip = "حَاذِراً<br>ADV<br>")`
`r tippy("قآئِماً", tooltip = "قَامَ<br>PTCP<br>Stem=I|Case=Acc|Definite=Ind|Gender=Masc|Number=Sing|Voice=Act")`
`r tippy("بِسَيْفِهِ", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِسَيْفِهِ", tooltip = "سَيْفٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("بِسَيْفِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("بِسَاحَةِ", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِسَاحَةِ", tooltip = "ساحَةٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("أّهْلِهِ", tooltip = "أّهْلٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("أّهْلِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَانْتَظَرَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَانْتَظَرَ", tooltip = "اِنْتَظَرَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=VIII")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("وَأَصْحَابُهُ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَأَصْحَابُهُ", tooltip = "صاحِبٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Plur")`
`r tippy("وَأَصْحَابُهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("أَنْ", tooltip = "أَنْ<br>CCONJ<br>")`
`r tippy("يَغْفُلَ", tooltip = "غَفَلَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("الْشَّيْخُ", tooltip = "شَيْخٌ<br>NOUN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("وَذٰلِكَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَذٰلِكَ", tooltip = "ذلِكَ<br>PRON<br>Gender=Masc|Number=Sing|PronType=Dem")`
`r tippy("آخِرَ", tooltip = "آخِرٌ<br>ADJ<br>Case=Acc|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("لَيْلَةٍ", tooltip = "لَيلَةٌ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("مِنَ", tooltip = "مِنْ<br>ADP<br>AdpType=Prep")`
`r tippy("الْشَّهْرِ", tooltip = "شَهْرٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("فَلَمَّا", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَلَمَّا", tooltip = "لَمَّا<br>CCONJ<br>")`
`r tippy("خَشُوا", tooltip = "خَشِيَ<br>VERB<br>ModAsp=Perf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("أَنْ", tooltip = "أَنْ<br>CCONJ<br>")`
`r tippy("يَفْضَحَهُمُ", tooltip = "فَضَحَ<br>VERB<br>ModAsp=Impf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("يَفْضَحَهُمُ", tooltip = "هُمْ<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("الصُّبْحُ", tooltip = "صُبْحٌ<br>NOUN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("وَلَمْ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَلَمْ", tooltip = "لم<br>PART<br>")`
`r tippy("يَقْدِرُوا", tooltip = "قَدَرَ<br>VERB<br>ModAsp=ـJuss|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("عَلَى", tooltip = "عَلَى<br>ADP<br>AdpType=Prep")`
`r tippy("غِرَّةٍ", tooltip = "غِرَّةٌ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("مَشَوْا", tooltip = "مَشَى<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("إِلَيْهِ", tooltip = "إِلى<br>ADP<br>AdpType=Prep")`
`r tippy("إِلَيْهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَغَرُّوهُ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَغَرُّوهُ", tooltip = "غَرَّ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("وَغَرُّوهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("بِبَقِيَّةِ", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِبَقِيَّةِ", tooltip = "بَقِيَّةِ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("الشَّهْرِ", tooltip = "شَهْرٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("الحَرَامِ", tooltip = "حَرَامٌ<br>ADJ<br>Case=Gen|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("وَأَعْطَوْهُ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَأَعْطَوْهُ", tooltip = "أَعْطَى<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Plur|Person=3|Voice=Act|Stem=IV")`
`r tippy("وَأَعْطَوْهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("مِنْ", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("مَوَاثِيقِهِمْ", tooltip = "مِيثَاقٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Plur")`
`r tippy("مَوَاثِيقِهِمْ", tooltip = "هُمْ<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("مَا", tooltip = "مَا<br>PRON<br>")`
`r tippy("أَقْنَعَهُ", tooltip = "أَقْنَعَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=IV")`
`r tippy("أَقْنَعَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَشَكَوْا", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَشَكَوْا", tooltip = "شَكا<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("إِلَيْهِ", tooltip = "إِلى<br>ADP<br>AdpType=Prep")`
`r tippy("إِلَيْهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("الْجُوعَ", tooltip = "جُوعٌ<br>NOUN<br>Case=Acc|Definite=Def|Number=Sing")`
`r tippy("فَلَمَّا", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَلَمَّا", tooltip = "لَمَّا<br>CCONJ<br>")`
`r tippy("آمَنُوا", tooltip = "آمَنَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Plur|Person=3|Voice=Act|Stem=IV")`
`r tippy("وَثَبُوا", tooltip = "وَثَبَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("عَلَيْهِ", tooltip = "على<br>ADP<br>AdpType=Prep")`
`r tippy("عَلَيْهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("فَقَتَلُوهُ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَقَتَلُوهُ", tooltip = "قَتَلَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("فَقَتَلُوهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَابْناً", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَابْناً", tooltip = "إبْنٌ<br>NOUN<br>Case=Acc|Definite=Ind|Number=Sing")`
`r tippy("لَهُ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("صَغِيراً", tooltip = "صَغيرٌ<br>ADJ<br>Case=Acc|Definite=Ind|Gender=Masc|Number=Sing")`
`r tippy("حِينَ", tooltip = "حِينَ<br>ADP<br>AdpType=Prep")`
`r tippy("مَشَى", tooltip = "مَشَى<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("وَمَضَى", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَمَضَى", tooltip = "مَضَى<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("إِلَى", tooltip = "إِلَى<br>ADP<br>AdpType=Prep")`
`r tippy("ابْنٍ", tooltip = "إبْنٌ<br>NOUN<br>Case=Gen|Definite=Ind |Number=Sing|")`
`r tippy("لَهُ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("ذى", tooltip = "ذو<br>PART<br>Case=Gen|Gender=Masc|Number=Sing|PronType=Rel")`
`r tippy("ذُؤَابَةٍ", tooltip = "ذُؤَابَةٌ<br>NOUN<br>Case=Nom|Definite=Ind|Number=Sing")`
`r tippy("كَانَ", tooltip = "كَانَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("أَبُوهُ", tooltip = "أَبٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Sing")`
`r tippy("أَبُوهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("قَدْ", tooltip = "قَدْ<br>PART<br>")`
`r tippy("أَمَرَهُ", tooltip = "أَمَرَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("أَمَرَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("فَارْتَبَأَ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَارْتَبَأَ", tooltip = "ارْتَبَأَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=VIII")`
`r tippy("مِنْ", tooltip = "مِنْ<br>ADP<br>AdpType=Prep")`
`r tippy("وَرَآءِ", tooltip = "وَرَآءَ<br>ADP<br>AdpType=Prep")`
`r tippy("مَالِهِ", tooltip = "مالٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("مَالِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("يُقَالُ", tooltip = "قَالَ<br>VERB<br>ModAsp=ـImpf|Gender=Masc|Number=Sing|Person=3|Voice=Pass")`
`r tippy("لَهُ", tooltip = "ل<br>ADP<br>AdpType=Prep")`
`r tippy("لَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("سُفْيَانُ بْنُ سَاعِدَةَ", tooltip = "سُفْيَانُ بْنُ سَاعِدَةَ<br>PROPN<br>Case=Nom|Definite=Ind|Number=Dual")`
`r tippy("فَأَقْبَلَ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَأَقْبَلَ", tooltip = "أقْبَلَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=IV")`
`r tippy("إِلَيْهِ", tooltip = "إلى<br>ADP<br>AdpType=Prep")`
`r tippy("إِلَيْهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("مُسْتَتِراً", tooltip = "مُسْتَتِرٌ<br>ADJ<br>Case=Acc|Definite=Ind|Gender=Masc|Number=Sing")`
`r tippy("بِمِجَنِّهِ", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِمِجَنِّهِ", tooltip = "مِجَنّ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("بِمِجَنِّهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("فَلَمَّا", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَلَمَّا", tooltip = "لَمَّا<br>CCONJ<br>")`
`r tippy("خَشِيَ", tooltip = "خَشِي<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("الْغُلَامُ", tooltip = "غُلامٌ<br>NOUN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("أَنْ", tooltip = "أَنَّ<br>CCONJ<br>")`
`r tippy("يَنَالَهُ", tooltip = "نالَ<br>VERB<br>ModAsp=ـSubj|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("يَنَالَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("بِسَيْفِهِ", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِسَيْفِهِ", tooltip = "سَيْفٌ<br>NOUN<br>Case=Gen|Definite=Cons|Number=Sing")`
`r tippy("بِسَيْفِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَلَيْسَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَلَيْسَ", tooltip = "لَيْسَ<br>PART<br>")`
`r tippy("مَعَ", tooltip = "مَعَ<br>ADP<br>AdpType=Prep")`
`r tippy("الْغُلَامِ", tooltip = "غُلامٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("سَيْفٌ", tooltip = "سَيْفٌ<br>NOUN<br>Case=Nom|Definite=Ind|Number=Sing")`
`r tippy("وَهُوَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَهُوَ", tooltip = "هُوَ<br>PRON<br>Gender=Masc|Number=Sing|Person=3")`
`r tippy("مُوفِقٌ", tooltip = "أَوْفَقَ<br>PTCP<br>Stem=IV|Case=Nom|Definite=Ind|Gender=Masc|Number=Sing|Voice=Act")`
`r tippy("بِسَهِمٍ", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِسَهِمٍ", tooltip = "سَهْمٌ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("رَمَى", tooltip = "رَمَى<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("مِجَنَّ", tooltip = "مِجَنّ<br>NOUN<br>Case=Acc|Definite=Cons|Number=Sing")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("بِحَجَمٍ", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِحَجَمٍ", tooltip = "حَجَمٌ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("فَظَنَّ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَظَنَّ", tooltip = "ظَنَّ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("أَنَّهُ", tooltip = "أنَّ<br>CCONJ<br>")`
`r tippy("أَنَّهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("قَدْ", tooltip = "قَدْ<br>PART<br>")`
`r tippy("أَرْسَلَ", tooltip = "أَرْسَلَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=IV")`
`r tippy("سَهْمَهُ", tooltip = "سَهْمٌ<br>NOUN<br>Case=Acc|Definite=Cons|Number=Sing")`
`r tippy("سَهْمَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("فَوَضَعَ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَوَضَعَ", tooltip = "وَضَعَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("الْمِجَنَّ", tooltip = "مِجَنّ<br>NOUN<br>Case=Acc|Definite=Def|Number=Sing")`
`r tippy("وَأَرْسَلَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَأَرْسَلَ", tooltip = "أَرْسَلَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=IV")`
`r tippy("الْغُلَامُ", tooltip = "غُلامٌ<br>NOUN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("السَّهْمَ", tooltip = "سَهْمٌ<br>NOUN<br>Case=Acc|Definite=Def|Number=Sing")`
`r tippy("فَلَمْ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَلَمْ", tooltip = "لَمْ<br>PART<br>")`
`r tippy("يُخْطِئْ", tooltip = "أَخْطَأَ<br>VERB<br>ModAsp=ـJuss|Gender=Masc|Number=Sing|Person=3|Voice=Act|Stem=IV")`
`r tippy("بِهِ", tooltip = "ب<br>ADP<br>AdpType=Prep")`
`r tippy("بِهِ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("لَبَّتَهُ", tooltip = "لَبَّةٌ<br>NOUN<br>Case=Acc|Definite=Cons|Number=Sing")`
`r tippy("لَبَّتَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("حَتَّى", tooltip = "حَتَّى<br>CCONJ<br>")`
`r tippy("خَرَجَ", tooltip = "خَرَجَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("مِنْهُ", tooltip = "مِنْ<br>ADP<br>AdpType=Prep")`
`r tippy("مِنْهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("السَّهْمُ", tooltip = "سَهْمٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("وَوَقَعَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَوَقَعَ", tooltip = "وَقَعَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("فى", tooltip = "فِي<br>ADP<br>AdpType=Prep")`
`r tippy("الْبَطْحَآءِ", tooltip = "بَطْحَاءُ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing|Gender=Fem")`
`r tippy("حَذْوَ", tooltip = "حَذْوَ<br>ADP<br>AdpType=Prep")`
`r tippy("الْقَوْمِ", tooltip = "قَوْمٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("وَأَبوهُ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَأَبوهُ", tooltip = "أَبٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Sing")`
`r tippy("وَأَبوهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("مُمْسَكٌ", tooltip = "أَمْسَكَ<br>PTCP<br>Stem=IV|Case=Nom|Definite=Ind|Gender=Masc|Number=Sing|Voice=Pass")`
`r tippy("فَقَالَ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَقَالَ", tooltip = "قالَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("أَبُوهُ", tooltip = "أَبٌ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Sing")`
`r tippy("أَبُوهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("حِينَ", tooltip = "حِينَ<br>ADP<br>AdpType=Prep")`
`r tippy("وَقَعَ", tooltip = "وَقَعَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("السَّهْمُ", tooltip = "سَهم<br>NOUN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("أَخَاطِئُهُ", tooltip = "أَ<br>PART<br>")`
`r tippy("أَخَاطِئُهُ", tooltip = "خَظِئَ<br>PTCP<br>Stem=I|Case=Nom|Definite=Cons|Gender=Masc|Number=Sing|Voice=Act")`
`r tippy("أَخَاطِئُهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("سُفْيَانُ", tooltip = "سُفْيَانُ<br>PROPN<br>")`
`r tippy("فَحَرِبَ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَحَرِبَ", tooltip = "حَرِبَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("الْقَوْمُ", tooltip = "قَوْمٌ<br>NOUN<br>Case=Nom|Definite=Def|Number=Sing")`
`r tippy("فَذٰلِكَ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَذٰلِكَ", tooltip = "ذلِكَ<br>PRON<br>Gender=Masc|Number=Sing|PronType=Dem")`
`r tippy("حِينَ", tooltip = "حِينَ<br>ADP<br>AdpType=Prep")`
`r tippy("قَتَلُوا", tooltip = "قَتَلَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("الشَّيْخَ", tooltip = "شَيخٌ<br>NOUN<br>Case=Acc|Definite=Def|Number=Sing")`
`r tippy("وَابْنَهُ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَابْنَهُ", tooltip = "ابن<br>NOUN<br>Case=Acc|Definite=Cons|Number=Sing")`
`r tippy("وَابْنَهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("الصَّغِيرَ", tooltip = "صَغِيرٌ<br>ADJ<br>Case=Acc|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("وَمَاتَ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَمَاتَ", tooltip = "ماتَ<br>VERB<br>ModAsp=ـPerf|Gender=Masc|Number=Sing|Person=3|Voice=Act")`
`r tippy("تَأَبَّطَ شَرّاً", tooltip = "تَأَبَّطَ شَرّاً<br>PROPN<br>")`
`r tippy("فَقَالَتْ", tooltip = "ف<br>CCONJ<br>")`
`r tippy("فَقَالَتْ", tooltip = "قالَ<br>VERB<br>ModAsp=ـPerf|Gender=Fem|Number=Sing|Person=3|Voice=Act")`
`r tippy("أُمُّهُ", tooltip = "أُمٌّ<br>NOUN<br>Case=Nom|Definite=Cons|Number=Sing")`
`r tippy("أُمُّهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("وَكَانَتِ", tooltip = "و<br>CCONJ<br>")`
`r tippy("وَكَانَتِ", tooltip = "كانَ<br>VERB<br>ModAsp=ـPerf|Gender=Fem|Number=Sing|Person=3|Voice=Act")`
`r tippy("امْرَأَةً", tooltip = "اِمرَأَةٌ<br>NOUN<br>Case=Acc|Definite=Ind|Number=Sing")`
`r tippy("مِنْ", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("بَني الْقَيْنِ ابْنِ جَسْرٍ", tooltip = "بَني الْقَيْنِ ابْنِ جَسْرٍ<br>PROPN<br>")`
`r tippy("ابْنِ جَسْرٍ", tooltip = "ابْنِ جَسْرٍ<br>PROPN<br>")`
`r tippy("مِنَ", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("الوافِر", tooltip = "الوافِرُ<br>NOUN<br>")`
`r tippy("قَتِيلٌ", tooltip = "قَتِيلٌ<br>ADJ<br>Case=Acc|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("مّا", tooltip = "مَا<br>PART<br>")`
`r tippy("قَتيلُ", tooltip = "قَتِيلٌ<br>ADJ<br>Case=Acc|Definite=Def|Gender=Masc|Number=Sing")`
`r tippy("بَني قُرَيْمٍ", tooltip = "بَني قُرَيْمٍ<br>PROPN<br>")`
`r tippy("إذا", tooltip = "إذا<br>CCONJ<br>")`
`r tippy("ضَنَّتْ", tooltip = "ضَنَّ<br>VERB<br>ModAsp=ـPerf|Gender=Fem|Number=Sing|Person=3|Voice=Act")`
`r tippy("جُمادى", tooltip = "جُمادى<br>PROPN<br>")`
`r tippy("بالْقِطارِ", tooltip = "بِ<br>ADP<br>AdpType=Prep")`
`r tippy("بالْقِطارِ", tooltip = "قِطارٌ<br>NOUN<br>Case=Gen|Definite=Def|Number=Sing")`
`r tippy("فَتى", tooltip = "فَتًى<br>NOUN<br>Case=Nom|Definite=Cons|Gender=Masc|Number=Sing")`
`r tippy("فَهْمٍ", tooltip = "فَهْمٌ<br>NOUN<br>Case=Gen|Definite=Ind|Number=Sing")`
`r tippy("جَميعًا", tooltip = "جَميعًا<br>ADV<br>")`
`r tippy("غادَرُوهُ", tooltip = "غادَرٌ<br>VERB<br>Stem=III|ModAsp=Perf|Gender=Masc|Number=Plur|Person=3|Voice=Act")`
`r tippy("غادَرُوهُ", tooltip = "ه<br>PRON<br>Gender=Masc|Number=Sing|Person=3|PronType=PersSuff")`
`r tippy("مُقيمًا", tooltip = "مُقيمٌ<br>ADJ<br>Case=Acc|Definite=Ind|Gender=Masc|Number=Sing")`
`r tippy("بِالْحُرَيْضَةِ", tooltip = "بِ<br>ADP<br>AdpType=Prep")`
`r tippy("بِالْحُرَيْضَةِ", tooltip = "الْحُرَيْضَةُ<br>PROPN<br>")`
`r tippy("مِن", tooltip = "مِن<br>ADP<br>AdpType=Prep")`
`r tippy("نُّمارِ", tooltip = "نُّمار<br>PROPN<br>")`
:::


## Словарь

::: {dir=rtl}


آخِرٌпоследний; آمَنَверить; أَвопросительная частица; أَبٌотец; أَبَىне желать, противиться, отказывать; أَبَىотказаться; أَحَدٌодин; أَخْطَأَошибаться; أَدْرَكَ; أَرَادَхотеть; أَرْسَلَотправлять, посылать; أَعْطَىбрать; أَغرَىпобуждать, настраивать; أَفزَعустрашать, тревожить; أقْبَلَподходить, приближаться; أَقْنَعَубедать уверять; أُمٌّмать; أمَرَприказывать; أَمَرَприказывать; أَمْسَكَдержать; أَمسىвечереть; أَمْسَىвечереть; أنَّ; أَنْ; أنَّчто; أَنَّчто; أَهْلٌнарод, люди; أّهْلٌнарод, люди; أَهْلٌсемья; أَهلٌсемья, народ; أَوْили; أَوсоюз или; أَوْفَقَприлаживать (стрелу); إبْنٌсын; إحْليلٌ; إِدَامٌ; إذاесли; إِلَّاкроме, исключая; إِلى; إِلَى; إلىк; إِلَىпредлог обознач.; إنْسانٌлюди; ابْنِ جَسْرٍ; ابنсын; اِتَّخَذَбрать; ارْتَبَأَнаблюдать с возвышения; اِسمٌимя; الْجَاهِلِيَّةДжахилия; الْجَاهِلِيَّةُДжахилия; الْحُرَيْضَةُ; القُرَمِيُّплемя Курайм; النُوَيْعِمٌ; الوافِرُвафир (стихотворный размер); الْيَوْمَсегодня; اِمرَأَةٌженщина; اِنْتَظَرَждать; اِنكَشَفَуходить,прекращаться, быть отстраненным от; ب; بِ; بпредлог; بَاتَночевать; بَصُرَзамечать, видеть; بَطْحَاءُдолина; بَقَرٌкорова, крупный рогатый скот; بَقِيَّةٌостаток; بَقِيَّةِостаток; بَلَدٌстрана; بَني الْقَيْنِ ابْنِ جَسْرٍ; بَنِي حَارِثَةَ بْنِ قُرَيْمٍ; بَني قُرَيْمٍ; بَنِي قريم; بَنِي قُرَيْمٍ; بَنِي نُفَاثَةَ; بَيْتٌдом; بَينَмежду; تَأَبَّطَ شَرّاً; تَأَبَّطَ شَرّاًТааббата Шарран; تَأَبَّطَбрать подмышку; تَعَدَّىпреступать, нарушать(закон); ثابِتُ بْنُ جابِرِ بْنِ سُفْيانَСабин бин Джабир бин Суфьян; ثُمَّзатем, потом; جَارٌсосед; جَبَلٌгора; جَريئٌсмелый; جَعَلَделать; جُمادىмесяц Джумада; جَمَاعَةٌгруппа, община; جُمّةٌженская прическа; جَميعًاвместе; جُنْدَبٌ; جُنْدَبُ بْنُ الْحٰرِثِ; جُوعٌголод; حَاذِراًосторожно; حَتَّى; حَتَّىдо; حَتَّىпока; حَتَّىпредлог до; حُثُنٍ; حَجَمٌразмер; حَذْوَнапротив; حَرَامٌзапрещённый; حَرِبَсердиться; حَرَّمَзапрещать, прекращать; حَصَرَокружать, сдерживать; حَلِيفٌсоюзный; حِمالَةٌперевязь, протупея; حِينَв то время как; حِينَкогда; خَرَجَвыходить, происходить из; خَشِيбояться, опасаться; خَشِيَбояться, опасаться; خَظِئَпромахнуться; خَعَلَделать; خَفَّضَснижать, сокращать; دِرْعٌброня кольчуга рубаха; دَعاзвать; دَعَاзвать; ذُؤَابَةٌчёлка; ذلِكَэто; ذٰلِكَэто; ذَنَبٌхвост, конец, нижняя часть; ذو; رَأسٌголова; رأىвидеть; راقَبَехать верхом; رَجُلٌмужчина; رَجُلٌчеловек; رِدآءٌплащ, верхняя мужская одежда; رَزَّвтыкать, вонзать; رَمَىбросать, кидать; زَالَпрекращать; ساحةٌдвор, площадь, открытая местность; ساحَةٌдвор, площадь, открытая местность; ساعِدَةٌ; سَاعِدةَ بْنِ سُفْيَانَ; سُفْيَانُ; سُفْيَانُ بْنُ سَاعِدَةَ; سِلْمٌмир, мирный; سَهمстрела; سَهْمٌстрела; سَيِّدٌгосподин; سَيْفٌмеч; شَأْنٌдело; شاذٌнеобычный, чужой; شاعِرٌпоэт; شِعْبٌущелье; شَكاжаловаться; شَهْرٌмесяц; شَيخٌшейх; شَيْخٌшейх; صاحَкричать; صاحِبٌспутник компаньон; صاهلة بِن كاهل بِن الحرث ابن تميم بِن سعد بِن هذيل; صُبْحٌутро рассвет; صَدْرٌгрудная клетка; صُرَيْمٌплемя Сурайм; صَغيرٌмаленький; صَغِيرٌмаленький; ضَحآءُпозднее утро, время до полудня; ضَنَّскупиться; طَرَدَизгонять, прогонять; طَلَعَвыходить, появляться; طَلَعَвыходить, появляться, подниматься; ظلّпродолжать; ظَنَّдумать; عَدْوَانُ; عُقْبٌконец; على; عَلى; عَلَى; علىна; عَلَىна; عُمُودٌшест от шатра; عَنْ; عَنْо; عَنْпредлог; غادَرٌпокинувший; غارةٌнападение; غَدَرَпредавать, отрекаться; غَرَّобманывать, обольщать; غِرَّةٌневнимательность оплошность; غَفَلَбыть беспечным, дремать; غُلامٌюноша, слуга; غَيْرَне, другой; فи; فَи; فاتِكٌхрабрый; فَتًى; فَضَحَобнаружить, сделать видимым; فِعْلٌдействие; فَهْمٌпонимание; فِي; فيв; فِيв; فِيпредлог; قالَсказать; قَالсказать; قَالَсказать; قَامَвставать; قامَвставать, подниматься; قَتَلَубить; قَتِيلٌубитый; قَد; قَدْ; قَدَرَсмочь; قِطارٌдождь; قَوْمٌнарод; ـكَ; كَкак; كَأَنَّمَاкак будто бы; كانَбыть; كَانَбыть; كَثِيرٌмногочисленный; كلвсе, весь; كُمْвы; كَمَاкак и; равно как, в равной степени; ل; لдля; لِдля; لِأَنْчтобы; لَبَّةٌверхняя часть груди у ключицы; لمне; لَمْне; لَمَّاкогда; لَيْسَне; لَيْسَнет; لَيلَةٌночь; لَيْلةٌночь; مَاкоторый; مَاчастица усиления; مَاчто; ماتَумирать; مالٌденьги, состояние; مَالٌденьги, состояние; مِجَنّщит; مَرَّпройти; مرأةженщина; مَرْأَةٌженщина; مُسْتَتِرٌскрытый, скрывающийся; مَشَىидти, ходить; مَصْدَرٌисточник; مَضَىуходить, проходить; مَعَпредлог с; вместе с; معс; مَعَс; مُقيمٌпроживающий; مِنиз; مِنْиз; مِيثَاقٌдоговор, пакт; نالَпобеждать, причинять зло; نَجَا; نِعْمةٌблагосостояние; نُفَاثَةَ بْنِ عَدِيٍّ; نَفْسٌсебя; نمارٌ; نُّمار; نَهْدٌотважный; نَهَضَвставать, подниматься; ه; هего; هон; هاней; هاон; هاона; هَبَطَопускаться; هذاэто; هُمْих (много мужчин); هُمْон; همони; هُمْони; هُماони (двое мужчин); هُماони (двух мужчин); هُنَّон; هنони (много женщин); هُنَّони (много женщин); هُوَон; هَيْئَةٌобраз; و; وи; وَи; وَاحِدٌодин; وَثَبَбросаться; وَجَدَнаходить; وَرَآءَза; وَشَلٌ; وَضَعَкласть; وَقَعَпадать; وَقَفَостанавливаться; وَلِيدَةٌдевушка; يмой; يَاчастица о!
:::


